@startuml
class MemberFeignController {
- MemberFeignService memberFeignService
+ ResponseResult memberQuery()
}


interface MemberFeignService {
~ ResponseResult memberQuery()
}

MemberFeignController -> MemberFeignService

@enduml