server:
  port: 80

spring:
  application:
    name: member-service-consumer-80

  #Swagger
  # After Springboot 2.6 version, you need to configure ant_path_matcher to make swagger work properly(适当地).
  # address: http://localhost:9191/swagger-ui/index.html
  mvc:
    path match:
      matching-strategy: ant_path_matcher


# knife4j
# address: http://localhost:9191/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn


#Eureka Client
eureka:
  client:
    # The default value is true, which means that the client will register with the eureka server.
    register-with-eureka: true
    # Get the service list from the eureka server.
    # If the server is cluster mode, must configure the value with true.
    fetch-registry: true
    # Register self to eureka server cluster.
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/