server:
  port: 10002

spring:
  application:
    name: member-service-provider
  # Zipkin
  zipkin:
    base-url: http://localhost:9411
  # Sleuth
  sleuth:
    sampler:
      #采样率在 0-1 之间，1 表示全部采集
      probability: 1

  # data
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# MybatisPlus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # map underscore
  #    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler   # EnumHandler
  global-config:
    db-config:
      id-type: auto  # Global id, if variable id don't have @TableId.
      update-strategy: not_null # Just update not null value.
      # Logic Delete
      logic-delete-field: deleted  # Globally Logic deletion
      logic-delete-value: 1      # Deleted value is 1
      logic-not-delete-value: 0   # Not deleted value is 0

# knife4j
# address: http://localhost:9191/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn

# Eureka Client
eureka:
  client:
    # The default value is true, which means that the client will register with the eureka server.
    register-with-eureka: true
    # Get the service list from the eureka server.
    # If the server is cluster mode, must configure the value with true.
    fetch-registry: true
    # Register self to eureka server.
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/, http://eureka9002.com:9002/eureka/






