server:
  port: 9002

spring:
  application:
    name: eureka-server-9002

# Client Web Access Address: http://localhost:9002/
eureka:
  instance:
    hostname: eureka9002.com   # ?????
  client:
    # 不用注册到 eureka 服务
    register-with-eureka: false
    # 表示自己就是注册中心，作用是维护注册服务实例，不需要检索服务。
    fetch-registry: false
    service-url:
      #  Register 9002 with 9001
      defaultZone: http://eureka9001.com:9001/eureka/
