server:
  port: 80

spring:
  application:
    name: member-openfeign-consumer-80

# knife4j
# address: http://localhost:9191/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn

#Eureka Client
eureka:
  client:
    # The default value is true, which means that the client will register with the eureka server.
    register-with-eureka: true
    # Get the service information list from the eureka server.
    fetch-registry: true
    # Register self to eureka server cluster.
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/